name: "Find terraform releases"
description: "Return names of latest terraform cli releases"
inputs:
  repo:
    required: true
    default: ""
    description: "Repo name in the form owner/name"
  min:
    required: false
    default: ""
    description: "The min version to consider, expressed in semver format"
  count:
    required: false
    default: "3"
    description: "The number of releases to return"

outputs:
  versions:
    description: "The json encoded array of release names"
    value: ${{steps.find-tf-releases.outputs.versions}}

runs:
  using: "composite"
  steps:
    - id: find-tf-releases
      uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08
      with:
        timeout_minutes: 2
        max_attempts: 5
        retry_wait_seconds: 10
        shell: bash
        command: |
          chmod +x .github/actions/find-github-releases/action.sh
          .github/actions/find-github-releases/action.sh --repo="${{inputs.repo}}" --min="${{inputs.min}}" --want="${{inputs.count}}"
