name: "Find clickhouse releases"
description: "Return names of latest clickhouse releases"
inputs: {}

outputs:
  versions:
    description: "The json encoded array of release names"
    value: ${{steps.find-ch-releases.outputs.versions}}

runs:
  using: "composite"
  steps:
    - id: find-ch-releases
      uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08
      with:
        timeout_minutes: 2
        max_attempts: 5
        retry_wait_seconds: 10
        shell: bash
        command: |
          chmod +x .github/actions/find-clickhouse-releases/action.sh
          .github/actions/find-clickhouse-releases/action.sh
