name: PR Comment Listener

on:
  issue_comment:
    types: [created]

jobs:
  check-comment:
    name: Parse action from comment
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Check comment
        id: action
        run: |
          case "${{ github.event.comment.body }}" in
          /test)
            echo "action=test" >> "$GITHUB_OUTPUT"
          ;;
          esac

      - name: Check Organization Membership
        if: ${{ steps.action.outputs.action != '' }}
        id: check-membership
        run: |
          ORG_NAME="${{ github.repository_owner }}"
          USERNAME="${{ github.event.comment.user.login }}"
          MEMBERSHIP_URL="https://api.github.com/orgs/$ORG_NAME/members/$USERNAME"

          RESULT=$(curl -L -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" $MEMBERSHIP_URL)

          echo "$RESULT"

          if echo "$RESULT" | jq -e '.state == "active"'; then
            echo "User ${{ github.event.comment.user.login }} is a member of $ORG_NAME"
          else
            echo "User ${{ github.event.comment.user.login }} is not a member of $ORG_NAME, skipping"
            exit 1
          fi

      - name: Trigger e2e tests
        if: ${{ steps.action.outputs.action == 'test' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run e2e.yml --ref "${{ github.ref_name }}"
