name: Run E2E tests

on:
  workflow_dispatch: {}

defaults:
  run:
    shell: bash

env:
  tf_release: "1.11.3"

jobs:
  list-examples:
    outputs:
      examples: ${{ steps.list.outputs.examples }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: list
        run: |
          examples="$(find examples/tests/ -name main.tf | xargs -n1 dirname | xargs -n1 basename| jq -cRn '[inputs]')"
          echo "examples=${examples}" >> "$GITHUB_OUTPUT"

  list-clickhouse-version:
    outputs:
      versions: ${{ steps.list.outputs.versions }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: list
        run: |
          set -o pipefail
          versions=()
          
          # Get list of most recent clickhouse OS version.
          RELEASES="$(curl -s -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/ClickHouse/clickhouse/releases|jq -r '.[] |.tag_name')"
          
          # Get major.minor of latest LTS and latest Stable releases.
          LATEST_LTS="$(echo "$RELEASES" | grep lts | sort -Vr |head -n1 | cut -d "." -f 1,2 | sed 's/v//')"
          LATEST_STABLE="$(echo "$RELEASES" | grep stable | sort -Vr |head -n1 | cut -d "." -f 1,2 | sed 's/v//')"
          
          versions+=(${LATEST_LTS})
          versions+=(${LATEST_STABLE})
          
          # Ensure no duplicate versions and turn into JSON.
          json="$(printf '%s\n' "${versions[@]}" | jq -R . | uniq |jq -cs .)"
          echo "versions=${json}" >> "$GITHUB_OUTPUT"

  list-terraform-version:
    outputs:
      versions: ${{ steps.list.outputs.releases }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/find-tf-releases
        id: list
        with:
          count: '3'

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Create tmp dir
        run: |
          TMPDIR="$(mktemp -d)"
          echo "TMPDIR=$TMPDIR" >> $GITHUB_ENV

      - name: Build terraform provider
        run: |
          CGO_ENABLED=0 go build -o $TMPDIR/terraform-provider-clickhousedbops
          
      - uses: actions/upload-artifact@v4
        with:
          name: terraform-provider-clickhousedbops
          path: ${{ env.TMPDIR }}

  e2e:
    runs-on: ubuntu-latest
    needs: ['build', 'list-examples', 'list-clickhouse-version', 'list-terraform-version']
    strategy:
      fail-fast: false
      matrix:
        terraform_version: ${{ fromJSON(needs.list-terraform-version.outputs.versions) }}
        clickhouse_version: ${{ fromJSON(needs.list-clickhouse-version.outputs.versions) }}
        protocol: ["native", "http"]
        example: ${{ fromJSON(needs.list-examples.outputs.examples) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: terraform-provider-clickhousedbops
          path: .

      - name: Adjust permissions
        run: |
          chmod +x ./terraform-provider-clickhousedbops
          ls -lah

      - name: Install terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform_version }}
          terraform_wrapper: false

      - name: Prepare test env
        run: |
          cd tests/
          export CLICKHOUSE_VERSION="${{ matrix.clickhouse_version }}"
          export TFVER="${{ matrix.terraform_version }}"
          export TF_VAR_protocol=${{ matrix.protocol }}
          
          case "$TF_VAR_protocol" in
            native)
              export TF_VAR_port=9000
              export TF_VAR_auth_strategy=password
              ;;
            http)
              export TF_VAR_port=8123
              export TF_VAR_auth_strategy=basicauth
              ;;
          esac
          
          docker compose up -d
          sleep 5
          
          # Check containers are running or display logs
          for svc in clickhouse shell ; do
            if [ -z $(docker compose ps -q $svc) ] || [ -z $(docker ps -q --no-trunc | grep $(docker compose ps -q $svc)) ]; then
              echo "Failed running $svc"
              docker compose logs $svc
              exit 1
            fi
          done
          
          docker compose exec clickhouse clickhouse client --password "test" "select version()"

      - name: Run e2e test
        run: |
          cd tests/
          export example=${{ matrix.example }}
          docker compose exec shell ash -c "cd $example && terraform apply -auto-approve && terraform destroy -auto-approve"

      - name: Stop test env
        if: always()
        run: |
          cd tests/
          docker compose kill
          docker compose rm -f

  notify:
    name: "E2E tests"
    runs-on: ubuntu-latest
    needs: ['e2e']
    if: always()
    steps:
      - name: Successful run
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0

      - name: Generate Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.WORKFLOW_AUTH_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_AUTH_PRIVATE_KEY }}

      - name: Send status check
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          state=""
          description=""
          if [ "${{ contains(needs.*.result, 'failure') }}" == "true" ]
          then
            state="error"
            description="E2E tests failed"
          else
            state="success"
            description="E2E tests succeeded"
          fi
          
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -f "state=$state" \
            -f "target_url=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
            -f "description=$description" \
            -f "context=E2E tests"
          
