name: Shellcheck

on:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  shellcheck:
    runs-on: k8s-nano
    name: Shellcheck
    steps:
      - name: Checkout repository code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4
      - name: Run
        run: |
          for FILE in $(find .github/actions -name '*.sh'); do
            echo "Running shellchek for ${FILE}"
            shellcheck "${FILE}"
          done
